### ISSUE TITLE
Update Embedded_PE to support finding PEs embedded in PEs

### ISSUE THREAD

**Issue by recvfrom** [InQuest/yara-rules#3]
Hello!

Currently, Embedded_PE will match on any PE header, which means it will always match when scanning an executable.  It might be more useful to have it exclude the PE header at offset zero so that the rule can be used to detect PEs embedded within PEs.  The following logic should achieve this:

```
        for any i in (1..#mz):
        (
            @mz[i] != 0 and uint32(@mz[i] + uint32(@mz[i] + 0x3C)) == 0x00004550
        )
```

**Comment by pedramamini** [comment]
@recvfrom thanks for your mindshare and apologies for the super late response here. not sure why but all of our public github.com notifications were basically going to `/dev/null`. Great signature and very immediately obvious to us that "Embedded_PE" is misleading here. Quick background on why this is the case. Before we run YARA, we expand files through a process we call "Deep File Inspection"... as it carves EXEs out of the data, those EXEs will indeed be embedded. We're going to update the repo to have two rules to make this more clear. Thanks!

**Comment by pedramamini** [comment]
https://github.com/InQuest/yara-rules/commit/be9ffac9026aee7a8b1e665e7c1e3bcbdda9eb79

**Comment by ghost** [comment]
Embedded_PE.rule and PE.rule have the same identifier

**Comment by pedramamini** [comment]
Good catch. Fixed:

https://github.com/InQuest/yara-rules/commit/fd87530863cca77384f37ae5485707a02207d715
